# Generated by Django 5.1.1 on 2024-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_role', models.CharField(max_length=255)),
                ('server_name', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=255)),
                ('ram', models.PositiveIntegerField()),
                ('datasource', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('diskdevices', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
