# Generated by Django 5.1.1 on 2024-10-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinfo',
            name='is_deleted',
        ),
    ]
