# Generated by Django 5.1.1 on 2024-10-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIapp', '0002_remove_serverinfo_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='ip',
            field=models.CharField(max_length=50),
        ),
    ]
